### ISSUE TITLE
ERR_UNHANDLED_REJECTION

### ISSUE THREAD

**Issue by PandelisZ** [sprusr/todoist-daily#1]
You're going to want to catch your rejections there bud. 

In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

https://github.com/sprusr/todoist-daily/blob/978150d0e8feed7c75c8284defc3d9445e6b1aab/src/pages/api/tasks.ts#L64

**Comment by sprusr** [comment]
#wontfix
